test:
  adapter: mysql
  database: troya37_test
  host: localhost
  username: root
  password: qwerty
  encoding: utf8
  timeout: 5000

development:
  adapter: mysql
  database: troya37_development
  host: localhost
  username: root
  password: qwerty
  encoding: utf8
  timeout: 5000

production:
  adapter: mysql
  database: troya37_production
  host: localhost
  username: root
  password: qwerty
  encoding: utf8
  timeout: 5000
